[tool.poetry]
name = "back"
version = "0.1.0"
description = ""
authors = ["Elmouatassim Louhaidia <mota@kraggin.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.85.1"
google-cloud-datastore = "^2.8.3"
requests = "^2.28.1"
uvicorn = "^0.18.3"
pydantic = {extras = ["email"], version = "^1.10.2"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
