baseURL: 'https://elmouatassim.louhaidia.info/'
author: elmouatassim

pagination:
  disableAliases: false
  pagerSize: 5
  path: page
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
disableHugoGeneratorInject: true
enableRobotsTXT: true

disableKinds: ["RSS"]

ignoreErrors:
  - error-remote-getjson

title: "mojo rojo"

params:
  color: linen
  github: mota-lhd
  instagram: m0jo.r0jo
  linkedin: elmouatassim-louhaidia
  threads: "@m0jo.r0jo"
  bluesky: m0jo-roj0.bsky.social
  comments: 'https://comments.louhaidia.info'
  avatar: "gravatar.foki2@passinbox.com"
  name: elmouatassim
  bio: >
    long distance runner, mountain lover and tech guy ğŸ‘¨ğŸ¼â€ğŸ’»
    currently in montpellier, south of france.
    feel free to get in touch.

markup:
  goldmark:
    renderer:
      unsafe: false

security:
  gotemplates:
    allowActionJSTmpl: true

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: categories
      name: categories
      url: /categories/
      weight: 30
    - identifier: series
      name: series
      url: /series/
      weight: 40

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  instagram:
    disabled: false
    simple: true

  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: true

services:
  instagram:
    disableInlineCSS: true
